name: Tests
on: [push, pull_request]

env:
  CI: true

jobs:
  run:
    name: Node ${{ matrix.node }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node: [6, 8, 10, 12]

    steps:
      - uses: actions/checkout@v2

      - name: Set Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Set up Ruby 2.4
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.4.x

      - name: Disable gem docs
        run: 'echo "gem: --no-document" > ~/.gemrc'

      - name: Set up Bundler
        run: gem install bundler -v "~> 1.17"

      - name: Update rubygems
        run: gem update --system

      - run: ruby --version
      - run: gem --version
      - run: bundle --version
      - run: node --version
      - run: npm --version

      - name: Install npm dependencies
        run: npm install

      - name: Set up Bootstrap repo
        run: |
          git clone --depth 1 https://github.com/twbs/bootstrap.git --branch v3-dev
          bundle install --deployment --path "$(pwd)/vendor/bundle" --gemfile bootstrap/Gemfile --jobs=3 --retry=3
          pushd bootstrap && bundle exec jekyll build && popd

      - name: Run tests with Coveralls
        run: npm run nyc -- npm run test && npm run qunit
        if: matrix.node == 10

      - name: Run tests
        run: npm test
        if: matrix.node != 10

      - name: Run extra tests
        run: |
          node ./src/cli-main.js --disable W003,W005 "bootstrap/_gh_pages/**/index.html"
          node ./src/cli-main.js test/fixtures/x-ua-compatible/missing.html &> x-ua-compatible-missing.output.actual.txt || true
          diff test/fixtures/cli/x-ua-compatible-missing.output.txt x-ua-compatible-missing.output.actual.txt

      - name: Run Coveralls
        run: npm run coveralls
        if: matrix.node == 10 && github.repository == 'twbs/bootlint' && github.event_name == 'push'
        env:
          COVERALLS_REPO_TOKEN: "${{ secrets.COVERALLS_REPO_TOKEN }}"
